@global = http://localhost:3000

POST  {{global}}/users/
Content-Type: application/json


{
  "name": {
    "first": "Ell22",
    "middle": "",
    "last": "Vi22s"
  },
  "phone": "0512345567",
  "email": "Admin222@hotmail.com",
  "password": "Abc!123Abc",
  "image": {
    "url": "",
    "alt": ""
  },
  "address": {
    "state": "IL",
    "country": "Israel",
    "city": "Arad",
    "street": "Shoham",
    "houseNumber": 5,
    "zip": "2151510"
  },
  "isBusiness": true

}


###

POST  {{global}}/users/login
Content-Type: application/json

{
  "email": "nick@gmail.com",
  "password": "Nick123456!"
}

###
GET {{global}}/users
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzg0ZDA3MjBjM2RhY2UzNTAyMzliZTIiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MzY3NTg1MTV9.IlEJ1zd_RM0zUH11CwgKKIkJdpVyk_av6l_wOP-9zaA
###

GET {{global}}/users/6784d0720c3dace350239be3
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzg0ZDA3MjBjM2RhY2UzNTAyMzliZTIiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MzY3NTg1MTV9.IlEJ1zd_RM0zUH11CwgKKIkJdpVyk_av6l_wOP-9zaA
###
PUT {{global}}/users/6784d0720c3dace350239be3
Content-Type: application/json
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzg0ZDA3MjBjM2RhY2UzNTAyMzliZTMiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzM2NzU4NzUyfQ.VyaoMuD2VyfLyGa-9zFdy0uI7lP3S7iY52xaeXXwr78

{
  "name": {
    "first": "Ell new222222222222",
    "middle": "",
    "last": "Vis new2222222222222"
  },
  "phone": "0512345567",
  "image": {
    "url": "",
    "alt": ""
  },
  "address": {
    "state": "IL2222",
    "country": "Israel",
    "city": "Arad",
    "street": "Shoham",
    "houseNumber": 5,
    "zip": "86444"
  }
}
###
PATCH  {{global}}/users/6784d0720c3dace350239be3
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzg0ZDA3MjBjM2RhY2UzNTAyMzliZTMiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzM2NzU4NzUyfQ.VyaoMuD2VyfLyGa-9zFdy0uI7lP3S7iY52xaeXXwr78

###
DELETE {{global}}/users/6784d30aacf23ae843eeccec
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzg0ZDA3MjBjM2RhY2UzNTAyMzliZTIiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MzY3NTg1MTV9.IlEJ1zd_RM0zUH11CwgKKIkJdpVyk_av6l_wOP-9zaA


###
POST {{global}}/cards/
Content-Type: application/json
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzg0ZDA3MjBjM2RhY2UzNTAyMzliZTMiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzM2NzU5MDA0fQ.tgnApx5qcvkMASgcvfFTZF-Zn-qKLYYogtTH8xMYlRY


{
  "title": "hellp",
  "subtitle": "hellp",
  "description": "a test value for new card\na test value for new card\n",
  "phone": "012-3211234",
  "email": "qwe@gmail.com",
  "web": "https://www.google22.com/",
  "image": {
    "url": "https://img.izismile.com/img/img13/20201030/640/you_have_never_seen_something_like_this_640_36.jpg",
    "alt": "image of something"
  },
  "address": {
    "state": "IL",
    "country": "Israel",
    "city": "Arad",
    "street": "Shoham",
    "houseNumber": 5,
    "zip": "8920435"
  }
}


###
GET {{global}}/cards/my-cards
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzg0ZDA3MjBjM2RhY2UzNTAyMzliZTMiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzM2NzU5MDA0fQ.tgnApx5qcvkMASgcvfFTZF-Zn-qKLYYogtTH8xMYlRY


###
GET {{global}}/cards/6784d6f35815a7edf21fce81


###
PUT {{global}}/cards/6784d6f35815a7edf21fce81
Content-Type: application/json
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzg0ZDA3MjBjM2RhY2UzNTAyMzliZTMiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzM2NzU5MDA0fQ.tgnApx5qcvkMASgcvfFTZF-Zn-qKLYYogtTH8xMYlRY

{
"title": "a wonderful new card updated!",
  "subtitle": "a test value for this card",
  "description": "a test value for new card\na test value for new card\n",
  "phone": "012-3211234",
  "email": "qwe@gmail.com",
  "web": "https://www.google22.com",
  "image": {
    "url": "https://img.izismile.com/img/img13/20201030/640/you_have_never_seen_something_like_this_640_36.jpg",
    "alt": "image of something"
  },
  "address": {
    "state": "IL",
    "country": "Israel",
    "city": "Arad",
    "street": "Shoham",
    "houseNumber": 5,
    "zip": "8920435"
  }

}


###
PATCH {{global}}/cards/6784d6f35815a7edf21fce81
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzg0ZDA3MjBjM2RhY2UzNTAyMzliZTMiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzM2NzU5MDA0fQ.tgnApx5qcvkMASgcvfFTZF-Zn-qKLYYogtTH8xMYlRY


### 
DELETE {{global}}/cards/6784d0720c3dace350239bec
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc1MWFlNzIwMTlkNGZmNDZhOWE1YWIiLCJpc0J1c2luZXNzIjpmYWxzZSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzM1ODE5OTg3fQ.VuFG2m5W2ZmOW1m0AWx0HZxM9-g1N__O-LB_KcKDKZs

### 
PATCH  {{global}}/cards/biz/6784d6f35815a7edf21fce81
Content-Type: application/json
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzg0ZDA3MjBjM2RhY2UzNTAyMzliZTIiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MzY3NTk0NzB9.6KHJXCykniwxGapKpO8xcYyHpi2WG0sDWJLKQgXJdUo

{
  "bizNumber":1000004
}
